# Generated by Django 3.2.13 on 2022-07-03 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_task_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
